//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuNhapKho
    {
        public int IdChitietPhieuNhapKho { get; set; }
        public Nullable<int> IdPhieuNhapKho { get; set; }
        public Nullable<int> IdThuoc { get; set; }
        public Nullable<int> SoLuongNhap { get; set; }
    
        public virtual PhieuNhapKho PhieuNhapKho { get; set; }
        public virtual PhieuNhapKho PhieuNhapKho1 { get; set; }
        public virtual PhieuNhapKho PhieuNhapKho2 { get; set; }
        public virtual Thuoc Thuoc { get; set; }
        public virtual Thuoc Thuoc1 { get; set; }
        public virtual Thuoc Thuoc2 { get; set; }
    }
}
