//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nhom_1.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DonBanHang
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DonBanHang()
        {
            this.ChiTietDonBanHangs = new HashSet<ChiTietDonBanHang>();
            this.ChiTietDonBanHangs1 = new HashSet<ChiTietDonBanHang>();
            this.ChiTietDonBanHangs2 = new HashSet<ChiTietDonBanHang>();
        }
    
        public int IdDonBanHang { get; set; }
        public System.DateTime NgayBan { get; set; }
        public Nullable<int> IdCuaHang { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonBanHang> ChiTietDonBanHangs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonBanHang> ChiTietDonBanHangs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietDonBanHang> ChiTietDonBanHangs2 { get; set; }
        public virtual CuaHang CuaHang { get; set; }
        public virtual CuaHang CuaHang1 { get; set; }
        public virtual CuaHang CuaHang2 { get; set; }
    }
}
